# Generated by Django 3.2.1 on 2021-05-15 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ssm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=225, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
