# Generated by Django 3.2.1 on 2021-05-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_ssm', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ssmuser',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1111111111, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to='main_ssm.user'),
            preserve_default=False,
        ),
    ]
