# Generated by Django 3.2.1 on 2021-05-25 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ssm', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date_blocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
