# Generated by Django 3.2.1 on 2021-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ssm', '0003_auto_20210525_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
