# Generated by Django 3.2.1 on 2021-05-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ssm', '0004_otp_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='usable',
            field=models.BooleanField(default=True),
        ),
    ]
