# Generated by Django 3.2.1 on 2021-05-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_ssm', '0006_rename_usable_otp_is_usable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='is_usable',
            new_name='is_latest',
        ),
    ]
