# Generated by Django 3.2.1 on 2021-05-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_ssm', '0007_rename_is_usable_otp_is_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('two_factor', 'Two Factor Authentication'), ('phone_verification', 'Phone Number Verification'), ('forgot_password', 'Forgot Password'), ('payment', 'Payment Authentication')], max_length=255),
        ),
    ]
